# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac39391f50298c3466ac55bb85bfc5ad24dadeca1022ea10bd4b5374b37ef23dc231d78c6a0a7788363c1b8ace1d4416f2ad9d90413b444d7836a609da2825c3

test:
  secret_key_base: 323fbf81da2c3f62d044c8ad9c5713ca3dedd712ca15bb8afc48c5b14a2859e1c857eca4ac7c8aaf7aceef37125229f8381dcabe2eda1f567d99c839f3b53e99

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
